//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Inventory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using global::IT_Inventory.Models;

    public partial class IT_Inventory : DbContext
    {
        public IT_Inventory()
            : base("name=IT_Inventory")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Departement> Departement { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Material_Group> Material_Group { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Material_Code> Material_Code { get; set; }
    }
}
