//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int User_Id { get; set; }
        public string Username { get; set; }
        public string Long_Name { get; set; }
        public string Password { get; set; }
        public string Departement { get; set; }
        public string City { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> Last_Login { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Edit_By { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public string Delete_By { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<bool> Is_Admin { get; set; }
    }
}
